
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-04-13 13:48:11
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace DapperTest.Model
{	
	public partial class Table1
    {
		

		/// <summary>
		/// 
		/// </summary>		
		public int Id { get; set; }
		

		/// <summary>
		/// 
		/// </summary>		
		public string name { get; set; }
		   
    }
}

