
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-04-03 14:36:48
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using DapperTest.Model;
using DapperTest.Data;

namespace DapperTest.Service
{	
	public partial class Table1Service
    {

        Table1Data dal = new Table1Data();

		/// <summary>
        /// 添加一条数据
        /// </summary>
        public int Add(Db_Table1 model)
        {
           return dal.Add(model);
        }

        /// <summary>
		/// 增加多条数据
		/// </summary>
		public bool AddBatch(List<Db_Table1>  model)
		{
			return dal.AddBatch(model) ;            
		}

		/// <summary>
        /// 更新一条数据
        /// </summary>
        public bool Update(Db_Table1 model)
        {
            return dal.Update(model);
        }
		

		/// <summary>
        /// 更新多条数据
        /// </summary>
        public bool UpdateBatch(List<Db_Table1> model)
        {
            return dal.UpdateBatch(model);
        }
		
		/// <summary>
        /// 删除一条数据
        /// </summary>
        public bool Delete(int  Id)
        {
            return dal.Delete(Id);
        }

        /// <summary>
        /// 删除多条数据
        /// </summary>
        public bool DeleteBatch(List<int>  Id)
        {
            return dal.DeleteBatch(Id);
        }

		/// <summary>
        /// 查询一个实体
        /// </summary>
        public Db_Table1 GetModel(int  Id)
        {
            return dal.GetModel(Id);
        }
		
		/// <summary>
        /// 根据条件查询所有实体
        /// </summary>
        public List<Db_Table1> GetModelList(string strWhere, object param = null)
        {
            return dal.GetModelList(strWhere,param);
        }

		/// <summary>
		/// 获取总条数
		/// </summary>
		/// <param name="strWhere"></param>
		/// <returns></returns>
		public int GetDataRecord(string strWhere, object param = null)
		{
			return dal.GetDataRecord(strWhere, param);
		}

		/// <summary>
		/// 分页获取数据列表
		/// </summary>
		public IEnumerable<Db_Table1> SelectListByPage(string strWhere, string orderby, int pageIndex, int pageSize,object param = null)
		{
			return dal.SelectListByPage(strWhere, orderby, pageIndex, pageSize, param);
		}
    }
}

