
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-04-03 14:43:28
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using DapperTest.Model;

namespace DapperTest.Data
{	
	public partial class Table1Data
    { 
		/// <summary>
		/// 增加一条数据
		/// </summary>
		public int Add(Db_Table1 model)
		{
			StringBuilder strSql = new StringBuilder();
			strSql.Append("INSERT INTO Table1(");			
            strSql.Append("Id,name");
			strSql.Append(")  OUTPUT  INSERTED.ID VALUES (");
            strSql.Append("@Id,@name");            
            strSql.Append(") "); 

			//var newClass = new
			//{
			//    Id = model.Id,
			//    name = model.name   
			//};   
			return (int)DapperHelper.ExecuteScalar(strSql.ToString(), model);            
		}
		
         /// <summary>
		/// 增加多条数据
		/// </summary>
		public bool AddBatch(List<Db_Table1>  model)
		{
			StringBuilder strSql = new StringBuilder();
			strSql.Append("INSERT INTO Table1(");			
            strSql.Append("Id,name");
			strSql.Append(")  OUTPUT  INSERTED.ID VALUES (");
            strSql.Append("@Id,@name");            
            strSql.Append(") "); 

		
			return DapperHelper.Excute(strSql.ToString(), model) > 0;            
		}
		
		/// <summary>
		/// 更新一条数据
		/// </summary>
		public bool Update(Db_Table1 model)
		{
			StringBuilder strSql = new StringBuilder();
			strSql.Append("UPDATE Table1 set ");        
            strSql.Append(" Id = @Id , ");        
            strSql.Append(" name = @name  ");			
			strSql.Append(" WHERE Id=@Id "); 


			return DapperHelper.Excute(strSql.ToString(), model) > 0; 
		}

	   /// <summary>
		/// 更新多条数据
		/// </summary>
		public bool UpdateBatch(List<Db_Table1> model)
		{
			StringBuilder strSql = new StringBuilder();
			strSql.Append("UPDATE Table1 set ");        
            strSql.Append(" Id = @Id , ");        
            strSql.Append(" name = @name  ");			
			strSql.Append(" WHERE Id=@Id "); 


			return DapperHelper.Excute(strSql.ToString(), model) > 0; 
		}
		
		
		
		/// <summary>
		/// 删除一条数据
		/// </summary>
		public bool Delete(int Id)
		{	
			StringBuilder strSql = new StringBuilder();
			strSql.Append("DELETE FROM Table1 ");
			strSql.Append(" WHERE Id=@Id");
			var newClass = new
			{
			    Id = Id   
			};   
			return DapperHelper.Excute(strSql.ToString(), newClass) > 0; 
		}

         /// <summary>
		/// 删除多条数据
		/// </summary>
         public bool DeleteBatch(List<int>  Id)
		{	
			StringBuilder strSql = new StringBuilder();
			strSql.Append("DELETE FROM Table1 ");
			strSql.Append(" WHERE Id in @Id");
            var newClass = new
			{
			    Id = Id   
			};   
			return DapperHelper.Excute(strSql.ToString(), newClass) > 0; 
		}
        


        /// <summary>
        /// 得到一个对象实体
        /// </summary>
        public Db_Table1 GetModel(int Id)
        {
            StringBuilder strSql = new StringBuilder();
            strSql.Append("SELECT Id,name ");
			strSql.Append(" FROM Table1 ");
            strSql.Append(" WHERE Id=@Id");
			var newClass = new
			{
			    Id = Id   
			};   
			return DapperHelper.FirstOrDefault<Db_Table1>(strSql.ToString(), newClass);
        }


		/// <summary>
        /// 获得数据列表
        /// </summary>
        public List<Db_Table1> GetModelList(string strWhere, object param = null)
        {
            StringBuilder strSql = new StringBuilder();
            strSql.Append("SELECT Id,name ");
			strSql.Append(" FROM Table1 ");
			if (strWhere.Trim() != "")
			{
			    strSql.Append(" WHERE " + strWhere);
			}   
			return DapperHelper.Query<Db_Table1>(strSql.ToString(), param);
        }


		/// <summary>
		/// 获取总条数
		/// </summary>
		/// <param name="strWhere"></param>
		/// <returns></returns>
		public int GetDataRecord(string strWhere, object param = null)
		{
		    string sql = "SELECT COUNT(1) FROM Table1 WHERE  " + strWhere;
		    object obj = DapperHelper.ExecuteScalar(sql, param );
		    if (obj == null)
		    {
		        return 0;
		    }
		    return Convert.ToInt32(obj);
		}

		/// <summary>
		/// 分页获取数据列表
		/// </summary>
		public IEnumerable<Db_Table1> SelectListByPage(string strWhere, string orderby, int pageIndex, int pageSize,object param = null)
		{
		    StringBuilder strSql = new StringBuilder();
		    strSql.Append("SELECT * FROM ( ");
		    strSql.Append(" SELECT ROW_NUMBER() OVER (");
		    if (!string.IsNullOrEmpty(orderby.Trim()))
		    {
		        strSql.Append("ORDER BY T." + orderby);
		    }
		    else
		    {
		        strSql.Append("ORDER BY T.id desc");
		    }
		    strSql.Append(")AS Row, T.* from Table1 T ");
		    if (!string.IsNullOrEmpty(strWhere.Trim()))
		    {
		        strSql.Append(" WHERE   " + strWhere);
		    }
		    strSql.Append(" ) TT");
		    strSql.AppendFormat(" WHERE TT.Row between {0} and {1}", (pageIndex-1)*pageSize+1,pageIndex * pageSize);

		    return DapperHelper.Query<Db_Table1>(strSql.ToString(), param);
		}
    }
}
